# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/facultate/licenta/fog_scratch2/src/ax7035b_fog.xdc

# Block Designs: F:/facultate/licenta/fog_scratch2/src/bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mipi_csi2_rx_subsystem_0_0 || ORIG_REF_NAME==design_1_mipi_csi2_rx_subsystem_0_0} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_pixel_counter_0_0/design_1_pixel_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pixel_counter_0_0 || ORIG_REF_NAME==design_1_pixel_counter_0_0} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_AXI_BayerToRGB_0_2/design_1_AXI_BayerToRGB_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI_BayerToRGB_0_2 || ORIG_REF_NAME==design_1_AXI_BayerToRGB_0_2} -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/ip/clk_200M/clk_200M.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_200M || ORIG_REF_NAME==clk_200M} -quiet] -quiet

# XDC: F:/facultate/licenta/fog_scratch2/src/bd/design_1/design_1_ooc.xdc

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/clk_200M/clk_200M_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_200M || ORIG_REF_NAME==clk_200M} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/clk_200M/clk_200M.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_200M || ORIG_REF_NAME==clk_200M} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/clk_200M/clk_200M_ooc.xdc
