# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "F:/facultate/licenta/fog_scratch2/vivado/fog_rectification.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/facultate/licenta/fog_scratch2/vivado/fog_rectification.cache/wt [current_project]
set_property parent.project_path F:/facultate/licenta/fog_scratch2/vivado/fog_rectification.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master [current_project]
update_ip_catalog
set_property ip_output_repo f:/facultate/licenta/fog_scratch2/vivado/fog_rectification.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property verilog_define VIDEO_1024_768 [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  F:/facultate/licenta/fog_scratch2/src/new/video_define.v
  F:/facultate/licenta/fog_scratch2/src/new/i2c_master/timescale.v
  F:/facultate/licenta/fog_scratch2/src/new/i2c_master/i2c_master_defines.v
}
set_property file_type "Verilog Header" [get_files F:/facultate/licenta/fog_scratch2/src/new/video_define.v]
set_property file_type "Verilog Header" [get_files F:/facultate/licenta/fog_scratch2/src/new/i2c_master/timescale.v]
set_property file_type "Verilog Header" [get_files F:/facultate/licenta/fog_scratch2/src/new/i2c_master/i2c_master_defines.v]
read_verilog -library xil_defaultlib {
  F:/facultate/licenta/fog_scratch2/src/airlight.v
  F:/facultate/licenta/fog_scratch2/src/new/aq_axi_master.v
  F:/facultate/licenta/fog_scratch2/src/bilateral_filter_t.v
  F:/facultate/licenta/fog_scratch2/src/new/cmos_write_req_gen.v
  F:/facultate/licenta/fog_scratch2/src/new/color_bar.v
  F:/facultate/licenta/fog_scratch2/src/contrast_stretch.v
  F:/facultate/licenta/fog_scratch2/src/dark_channel.v
  F:/facultate/licenta/fog_scratch2/vivado/fog_rectification.srcs/sources_1/imports/hdl/design_1_wrapper.v
  F:/facultate/licenta/fog_scratch2/src/fog_pipeline.v
  F:/facultate/licenta/fog_scratch2/src/new/frame_fifo_read.v
  F:/facultate/licenta/fog_scratch2/src/new/frame_fifo_write.v
  F:/facultate/licenta/fog_scratch2/src/new/frame_read_write.v
  F:/facultate/licenta/fog_scratch2/src/gaussian_filter_t.v
  F:/facultate/licenta/fog_scratch2/src/new/i2c_master/i2c_config.v
  F:/facultate/licenta/fog_scratch2/src/new/i2c_master/i2c_master_bit_ctrl.v
  F:/facultate/licenta/fog_scratch2/src/new/i2c_master/i2c_master_byte_ctrl.v
  F:/facultate/licenta/fog_scratch2/src/new/i2c_master/i2c_master_top.v
  F:/facultate/licenta/fog_scratch2/src/new/lut_ov5640_rgb565_1024_768.v
  F:/facultate/licenta/fog_scratch2/src/restoration.v
  F:/facultate/licenta/fog_scratch2/src/transmission_map.v
  F:/facultate/licenta/fog_scratch2/src/new/video_timing_data.v
  F:/facultate/licenta/fog_scratch2/src/top.v
}
read_vhdl -library xil_defaultlib {
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/ClockGen.vhd
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/DVI_Constants.vhd
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/OutputSERDES.vhd
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/SyncAsync.vhd
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/SyncAsyncReset.vhd
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/TMDS_Encoder.vhd
  F:/facultate/licenta/fog_scratch2/vivado-library-master/vivado-library-master/ip/rgb2dvi/src/rgb2dvi.vhd
}
add_files F:/facultate/licenta/fog_scratch2/src/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/bd_bf15_phy_0.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/bd_bf15_phy_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/bd_bf15_phy_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/ip_0/bd_bf15_vfb_0_0_axisswitch_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/bd_bf15_vfb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf15_r_sync_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf15_r_sync_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/bd_bf15_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_fixed_impl.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_fixed_impl.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_fixed_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/fog_scratch2/src/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/facultate/licenta/fog_scratch2/src/bd/design_1/design_1_ooc.xdc]

read_ip -quiet F:/facultate/licenta/fog_scratch2/src/ip/clk_200M/clk_200M.xci
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/clk_200M/clk_200M_board.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/clk_200M/clk_200M.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/clk_200M/clk_200M_ooc.xdc]

read_ip -quiet F:/facultate/licenta/fog_scratch2/src/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_late.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_ooc.xdc]

read_ip -quiet F:/facultate/licenta/fog_scratch2/src/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

read_ip -quiet F:/facultate/licenta/fog_scratch2/src/new/ip/afifo_64i_16o_128/afifo_64i_16o_128.xci
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_64i_16o_128/afifo_64i_16o_128.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_64i_16o_128/afifo_64i_16o_128_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_64i_16o_128/afifo_64i_16o_128_ooc.xdc]

read_ip -quiet F:/facultate/licenta/fog_scratch2/src/new/ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/facultate/licenta/fog_scratch2/src/ax7035b_fog.xdc
set_property used_in_implementation false [get_files F:/facultate/licenta/fog_scratch2/src/ax7035b_fog.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental F:/facultate/licenta/fog_scratch2/vivado/fog_rectification.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
