# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/facultate/licenta/fog_scratch2/src/new/ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
# IP: The module: 'afifo_16i_64o_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/new/ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
# IP: The module: 'afifo_16i_64o_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/new/ip/afifo_16i_64o_512/afifo_16i_64o_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
