# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/facultate/licenta/fog_scratch2/src/ip/video_pll/video_pll.xci
# IP: The module: 'video_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/facultate/licenta/fog_scratch2/src/ip/video_pll/video_pll.xci
# IP: The module: 'video_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/facultate/licenta/ax7035_mipi.gen/sources_1/ip/video_pll/video_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
